friends_project/urls.py
from django.contrib import admin
from django.urls import path, include

from .settings import ConfigClass


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

if ConfigClass.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('<pk>', views.UserDetailView.as_view(), name='detail'),
]

users/models.py
from django.db import models
from django.db.models import CharField, DateField, SlugField, TextField
from django.db.models import DateTimeField, CharField, ForeignKey
from django.db.models import ManyToManyField

from django.utils import timezone


# Примеры заполнения моделей смотрите в модулях factories и management.commands
class User(models.Model):
    username = SlugField(max_length=50, unique=True)
    name = CharField(max_length=200)
    birthday = DateField(null=True, blank=True)
    friends = ManyToManyField('self')

    def __str__(self):
        return '{}: {}'.format(self.username, self.name)


class RequestFriend(models.Model):
    STATUS_CHOICES = (
        ('accept', 'Принят'),
        ('deny', 'Отказ'),
        ('none', 'Запрос'),
    )
    from_user = ForeignKey(
        'User', related_name='request_friends_send', on_delete=models.CASCADE
    )
    to_user = ForeignKey(
        'User', related_name='request_friends_recv', on_delete=models.CASCADE
    )
    message = TextField(blank=True)
    datetime_request = DateTimeField(default=timezone.now)
    datetime_accept = DateTimeField(null=True, blank=True)
    status = CharField(
        max_length=6, choices=STATUS_CHOICES, default='none'
    )

    def accept_request(self):
        self.from_user.friends.add(self.to_user)
        self.status = 'accept'
        self.datetime_accept = timezone.now
        self.save()

    def deny_request(self):
        self.status = 'deny'
        self.save()

users/views.py
from django.views.generic import ListView, DetailView

from .models import User


class UserListView(ListView):
    model = User
    template_name = 'users/users_list.html'


class UserDetailView(DetailView):
    model = User
    template_name = 'users/users_detail.html'

users/templates/users/users_detail.html
<!doctype html>
<html lang="en">
  <head>
    <title>freinds</title>
  </head>

  <body>

    <h1>{{ object.name }} ({{ object.username }})</h1>
    <h2>Друзья</h2>
    <ul>
      {% for freind in object.freinds.all %}
        <li>
          <a href="{% url 'users:detail' freind.id %}">{{ freind.username }} - {{ freind.name }}</a>
        </li>
      {% endfor %}
    </ul>
    <h2>Отправлено приглашений</h2>
    <ul>
      {% for request in object.request_freinds_send.all %}
        <li>
          {{ request.to_user }} - {{ request.datetime_request }} ({{ request.status }})
        </li>
      {% endfor %}
    </ul>
  </body>
</html>

users/templates/users/users_list.html
<!doctype html>
<html lang="en">
  <head>
    <title>freinds</title>
  </head>

  <body>
    <h1>Список пользователей</h1>
    <ul>
      {% for user in object_list %}
      <li>
        <a href="{% url 'users:detail' user.id %}">{{ user.username }} - {{ user.name }}</a>
      </li>
      {% endfor %}
    </ul>
  </body>
</html>